title: 22 Digital Form Support
timezone: Africa/Johannesburg
description: The 22 Digital Form Support website is the official support channel for https://forms.22digital.tech. The support website  provides various FAQs and test forms for you to play around with.
url: https://formtest.22digital.tech
theme: jekyll-theme-minimal
logo: https://forms-22digital.herokuapp.com/static/img/logo.png
show_downloads: true
google_analytics: UA-100937492-4
collections:
  posts:
    title                     : Posts
    output                    : true
    permalink                 : /:categories/:title.html
  pages:
    title                     : Pages
    output                    : true
    permalink                 : /:categories/:title.html
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-last-modified-at
- jekyll-redirect-from
- jekyll-paginate
exclude:
- ".github"
- ".sass-cache"
- _site
- ".gitignore"
- ".travis.yml"
- 22digital.sublime-project
- 22digital.code-workspace
- 22digital.sublime-workspace
- CHANGELOG.md
- CNAME
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- _templates
- vendor
locale                        : "en_ZA"
# Pagination
paginate                      : 5
paginate_path                 : /all/page:num/
